# Generated by Django 3.2.5 on 2021-07-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-desc',)},
        ),
    ]
